name: nullx_list
homepage: https://shtanko.dev
description: >-
  nullx_list is a collection of elegant extensions for handling null types on Dart collection types.
version: 0.2.2
repository: https://github.com/ashtanko/nullx/nullx_list
resolution: workspace

environment:
  sdk: ^3.5.0

topics:
  - null-safety
  - nullable
  - types
  - collections

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  async: ^2.10.0
  nullx_iterable: ^0.2.0

dev_dependencies:
  lint: '>=1.5.0 <3.0.0'
  test: ^1.16.4
