name: nullx_workspace
environment:
  sdk: ^3.5.0
publish_to: none
dev_dependencies:
  lint: '>=1.5.0 <3.0.0'

workspace:
  - nullx_stream
  - nullx_map
  - nullx_either
  - nullx_runes
  - nullx_object
  - nullx_list
  - nullx_iterable
  - nullx_future
  - nullx_function
  - nullx_types
  - nullx_utils
  - example
