name: nullx
homepage: https://shtanko.dev
description: >-
  nullx is a collection of elegant extensions for handling null types in Dart.
version: 0.1.7
repository: https://github.com/ashtanko/nullx

topics:
  - null-safety
  - nullable
  - types
  - collections

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: '>=1.5.0 <3.0.0'
  test: ^1.16.4
