name: nullx_iterable
homepage: https://shtanko.dev
description: >-
  nullx_iterable is a collection of elegant extensions for handling null types on Dart iterable types.
version: 0.2.1
repository: https://github.com/ashtanko/nullx/nullx_iterable
resolution: workspace

environment:
  sdk: ^3.5.0

topics:
  - null-safety
  - nullable
  - types
  - collections

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  async: ^2.10.0

dev_dependencies:
  lint: '>=1.5.0 <3.0.0'
  test: ^1.16.4
