name: Dart CI

on: [ push, pull_request ]

jobs:
  correctness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: dart-lang/setup-dart@c8d9f105c780f626b21f6929fec7e8162014f5ad
        with:
          sdk: dev
      - name: Install dependencies
        run: dart pub upgrade
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze --fatal-infos

  test-os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        sdk: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
      - uses: dart-lang/setup-dart@c8d9f105c780f626b21f6929fec7e8162014f5ad
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub upgrade
      - name: Run Tests
        run: dart test

  test-versions:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [ "2.18", "2.19", "3.0", "beta" ]

    container:
      image: dart:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test

  test-windows:
    timeout-minutes: 5
    runs-on: windows-latest

    steps:
      - name: Install dart
        run: |
          choco install dart-sdk
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: C:\tools\dart-sdk\bin\dart.exe pub get
      - name: Run tests
        run: C:\tools\dart-sdk\bin\dart.exe pub run test

  test-macos:
    timeout-minutes: 5
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5
      - name: Tap Google's Dart formula repository
        run: brew tap dart-lang/dart
      - name: Install the Dart formula
        run: brew install dart
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart pub run test
