name: Coverage

on: [ push, pull_request ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    container:
      image: dart:3.7

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dart pub get
      - name: Collect coverage
        run: |
          dart pub global activate coverage
          dart pub global run coverage:test_with_coverage

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: coverage/lcov.info
          min_coverage: 80

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
